version: '3.7'
x-database-env-variables: &postgresConnect
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  postgres:
    build:
      dockerfile: ./Dockerfile
      context: ./postgres
    restart: always
    environment: 
      <<: *postgresConnect
    networks:
      - callendar-api
    ports:
      - '5552:5432'
    volumes:
      - ./postgres/create_database:/app/create

networks:
   callendar-api:
    driver: bridge